# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.disableMaxExtentConstaintCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.disableMaxExtentConstaintCheckBox.setObjectName("disableMaxExtentConstaintCheckBox")
        self.gridLayout_4.addWidget(self.disableMaxExtentConstaintCheckBox, 1, 0, 1, 1)
        self.applyConstaintsCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.applyConstaintsCheckBox.setObjectName("applyConstaintsCheckBox")
        self.gridLayout_4.addWidget(self.applyConstaintsCheckBox, 0, 0, 1, 1)
        self.setConstraintsBlockingCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.setConstraintsBlockingCheckBox.setObjectName("setConstraintsBlockingCheckBox")
        self.gridLayout_4.addWidget(self.setConstraintsBlockingCheckBox, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.recreateTableRB = QtWidgets.QRadioButton(self.groupBox)
        self.recreateTableRB.setObjectName("recreateTableRB")
        self.gridLayout_8.addWidget(self.recreateTableRB, 2, 0, 1, 1)
        self.createTableOnlyRB = QtWidgets.QRadioButton(self.groupBox)
        self.createTableOnlyRB.setObjectName("createTableOnlyRB")
        self.gridLayout_8.addWidget(self.createTableOnlyRB, 3, 0, 1, 1)
        self.appendToNewTableRB = QtWidgets.QRadioButton(self.groupBox)
        self.appendToNewTableRB.setObjectName("appendToNewTableRB")
        self.gridLayout_8.addWidget(self.appendToNewTableRB, 1, 0, 1, 1)
        self.createNewTableRB = QtWidgets.QRadioButton(self.groupBox)
        self.createNewTableRB.setObjectName("createNewTableRB")
        self.gridLayout_8.addWidget(self.createNewTableRB, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.inputPathLabel = QtWidgets.QLabel(self.groupBox_5)
        self.inputPathLabel.setObjectName("inputPathLabel")
        self.gridLayout_9.addWidget(self.inputPathLabel, 0, 0, 1, 1)
        self.inputPathInput = QtWidgets.QLineEdit(self.groupBox_5)
        self.inputPathInput.setObjectName("inputPathInput")
        self.gridLayout_9.addWidget(self.inputPathInput, 0, 1, 1, 1)
        self.tifCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.tifCheckBox.setObjectName("tifCheckBox")
        self.gridLayout_9.addWidget(self.tifCheckBox, 1, 1, 1, 1)
        self.recursiveSearchCheckBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.recursiveSearchCheckBox.setObjectName("recursiveSearchCheckBox")
        self.gridLayout_9.addWidget(self.recursiveSearchCheckBox, 1, 0, 1, 1)
        self.imgChecKBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.imgChecKBox.setObjectName("imgChecKBox")
        self.gridLayout_9.addWidget(self.imgChecKBox, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_5, 0, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.OOBRasterCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.OOBRasterCheckBox.setObjectName("OOBRasterCheckBox")
        self.gridLayout_5.addWidget(self.OOBRasterCheckBox, 4, 0, 1, 1)
        self.createOverviewsCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.createOverviewsCheckBox.setObjectName("createOverviewsCheckBox")
        self.gridLayout_5.addWidget(self.createOverviewsCheckBox, 5, 0, 1, 1)
        self.overviewInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.overviewInput.setObjectName("overviewInput")
        self.gridLayout_5.addWidget(self.overviewInput, 5, 1, 1, 1)
        self.extractBandCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.extractBandCheckBox.setObjectName("extractBandCheckBox")
        self.gridLayout_5.addWidget(self.extractBandCheckBox, 1, 0, 1, 1)
        self.setSRIDCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.setSRIDCheckBox.setObjectName("setSRIDCheckBox")
        self.gridLayout_5.addWidget(self.setSRIDCheckBox, 0, 0, 1, 1)
        self.tileSizeCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.tileSizeCheckBox.setObjectName("tileSizeCheckBox")
        self.gridLayout_5.addWidget(self.tileSizeCheckBox, 2, 0, 1, 1)
        self.tileSizeInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.tileSizeInput.setObjectName("tileSizeInput")
        self.gridLayout_5.addWidget(self.tileSizeInput, 2, 1, 1, 1)
        self.extractBandInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.extractBandInput.setObjectName("extractBandInput")
        self.gridLayout_5.addWidget(self.extractBandInput, 1, 1, 1, 1)
        self.padTilesCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.padTilesCheckBox.setObjectName("padTilesCheckBox")
        self.gridLayout_5.addWidget(self.padTilesCheckBox, 3, 0, 1, 1)
        self.SRIDInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.SRIDInput.setObjectName("SRIDInput")
        self.gridLayout_5.addWidget(self.SRIDInput, 0, 1, 1, 1)
        self.setNoDataCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.setNoDataCheckBox.setObjectName("setNoDataCheckBox")
        self.gridLayout_5.addWidget(self.setNoDataCheckBox, 6, 0, 1, 1)
        self.noDataValueInput = QtWidgets.QLineEdit(self.groupBox_3)
        self.noDataValueInput.setObjectName("noDataValueInput")
        self.gridLayout_5.addWidget(self.noDataValueInput, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.specifyTablespaceCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.specifyTablespaceCheckBox.setObjectName("specifyTablespaceCheckBox")
        self.gridLayout_6.addWidget(self.specifyTablespaceCheckBox, 7, 0, 1, 1)
        self.addFIlenameToColumnNameCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.addFIlenameToColumnNameCheckBox.setObjectName("addFIlenameToColumnNameCheckBox")
        self.gridLayout_6.addWidget(self.addFIlenameToColumnNameCheckBox, 2, 0, 1, 1)
        self.skipNoDataChecksBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.skipNoDataChecksBox.setObjectName("skipNoDataChecksBox")
        self.gridLayout_6.addWidget(self.skipNoDataChecksBox, 6, 0, 1, 1)
        self.columnNameCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.columnNameCheckBox.setObjectName("columnNameCheckBox")
        self.gridLayout_6.addWidget(self.columnNameCheckBox, 0, 0, 1, 1)
        self.addFilenameToColumnCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.addFilenameToColumnCheckBox.setObjectName("addFilenameToColumnCheckBox")
        self.gridLayout_6.addWidget(self.addFilenameToColumnCheckBox, 1, 0, 1, 1)
        self.columnNameInput = QtWidgets.QLineEdit(self.groupBox_4)
        self.columnNameInput.setObjectName("columnNameInput")
        self.gridLayout_6.addWidget(self.columnNameInput, 0, 1, 1, 1)
        self.filenameColumnNameInput = QtWidgets.QLineEdit(self.groupBox_4)
        self.filenameColumnNameInput.setObjectName("filenameColumnNameInput")
        self.gridLayout_6.addWidget(self.filenameColumnNameInput, 2, 1, 1, 1)
        self.vacuumAnalyzeCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.vacuumAnalyzeCheckBox.setObjectName("vacuumAnalyzeCheckBox")
        self.gridLayout_6.addWidget(self.vacuumAnalyzeCheckBox, 5, 0, 1, 1)
        self.createGISTIndexCheckbox = QtWidgets.QCheckBox(self.groupBox_4)
        self.createGISTIndexCheckbox.setObjectName("createGISTIndexCheckbox")
        self.gridLayout_6.addWidget(self.createGISTIndexCheckbox, 4, 0, 1, 1)
        self.wrapPgIDinQuotesCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.wrapPgIDinQuotesCheckBox.setObjectName("wrapPgIDinQuotesCheckBox")
        self.gridLayout_6.addWidget(self.wrapPgIDinQuotesCheckBox, 3, 0, 1, 1)
        self.specifyTablespaceForIndexCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.specifyTablespaceForIndexCheckBox.setObjectName("specifyTablespaceForIndexCheckBox")
        self.gridLayout_6.addWidget(self.specifyTablespaceForIndexCheckBox, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "R2PG-GUI"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Constaint Options"))
        self.disableMaxExtentConstaintCheckBox.setText(_translate("MainWindow", "Disable max extent constraint (x)"))
        self.applyConstaintsCheckBox.setText(_translate("MainWindow", "Apply constraints (C)"))
        self.setConstraintsBlockingCheckBox.setText(_translate("MainWindow", "Set constaints for regular blocking (r)"))
        self.groupBox.setTitle(_translate("MainWindow", "Creation Options"))
        self.recreateTableRB.setText(_translate("MainWindow", "Recreate table (d)"))
        self.createTableOnlyRB.setText(_translate("MainWindow", "Only create table (p)"))
        self.appendToNewTableRB.setText(_translate("MainWindow", "Append to table (a)"))
        self.createNewTableRB.setText(_translate("MainWindow", "Create new table (c)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Input"))
        self.inputPathLabel.setText(_translate("MainWindow", "Input Path"))
        self.tifCheckBox.setText(_translate("MainWindow", "Tif"))
        self.recursiveSearchCheckBox.setText(_translate("MainWindow", "Recursive search"))
        self.imgChecKBox.setText(_translate("MainWindow", "Img"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Raster Processing Options"))
        self.OOBRasterCheckBox.setText(_translate("MainWindow", "Register as out-of-db raster (R)"))
        self.createOverviewsCheckBox.setText(_translate("MainWindow", "Create overviews (l)"))
        self.extractBandCheckBox.setText(_translate("MainWindow", "Extract band (b)"))
        self.setSRIDCheckBox.setText(_translate("MainWindow", "Set SRID (s)"))
        self.tileSizeCheckBox.setText(_translate("MainWindow", "Set tile size (t)"))
        self.padTilesCheckBox.setText(_translate("MainWindow", "Pad right & bottom tiles (P)"))
        self.setNoDataCheckBox.setText(_translate("MainWindow", "Set NODATA value (N)"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Optional parameters"))
        self.specifyTablespaceCheckBox.setText(_translate("MainWindow", "Specify tablespace (T)"))
        self.addFIlenameToColumnNameCheckBox.setText(_translate("MainWindow", "Filename column name (n)"))
        self.skipNoDataChecksBox.setText(_translate("MainWindow", "Skip nodata checks (k)"))
        self.columnNameCheckBox.setText(_translate("MainWindow", "Column name (f)"))
        self.addFilenameToColumnCheckBox.setText(_translate("MainWindow", "Add filename to column (F)"))
        self.vacuumAnalyzeCheckBox.setText(_translate("MainWindow", "Vacuum analyze (M)"))
        self.createGISTIndexCheckbox.setText(_translate("MainWindow", "Create GiST index (I)"))
        self.wrapPgIDinQuotesCheckBox.setText(_translate("MainWindow", "Wrap PG IDs in quotes (q)"))
        self.specifyTablespaceForIndexCheckBox.setText(_translate("MainWindow", "Specify tablespace for new index (X)"))

